In [9]:
import numpy as np

n_pi = 20
spt = 2
T = 1000.
target_Azz= 0.01
rabi_period=0.2

def pulse_locations(n_pi=None, spt=None):
    """
    outputs pulse_locations - np.one, e.g. n_pi = 20, spt = 1 --> [1, 4, 7, 10.. 58]
    """
    return np.arange(spt, 2*n_pi*spt + n_pi, 2*spt + 1, dtype=int)

pulse_locations(n_pi=n_pi, spt=spt)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [10]:
def l_active(n_pi=None, spt=None):
    out = np.ones([2 * n_pi * spt + n_pi])
    out[pulse_locations(n_pi=n_pi, spt=spt)] = 0.
    return out

l_active(n_pi=n_pi, spt=spt)

array([ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.])

In [11]:
def tau(T=None, n_pi=None, spt=None):
    return T/(2*n_pi*spt)

tau(T=T, n_pi=n_pi, spt=spt)

12.5

In [12]:
def alpha(T=None, n_pi=None, n=None, target_Azz=None, spt=None, rabi_period=None):
    delta_alpha = 2*np.pi*target_Azz*(tau(T=T, n_pi=n_pi, spt=spt)*spt + 0.25*rabi_period)
    return int(np.ceil(n/2.))*(delta_alpha + np.pi) % (2*np.pi)

alpha(T=T, n=1, target_Azz=target_Azz, spt=spt, rabi_period=rabi_period, n_pi=n_pi)

4.715530573038279

In [13]:
def u_array(T=None, n_pi=None, spt=None, target_Azz=None, rabi_period=None):
    omega = 0.5 / T
    u_phi = [alpha(T=T, n_pi=n_pi, n=n, target_Azz=target_Azz, spt=spt, rabi_period=rabi_period) for n in range(2*n_pi)]
    u_x = np.array([omega * np.cos(phi) for phi in u_phi])
    u_x = np.tile([u_x for i in range(spt)], 1).T.reshape(-1)
    u_y = np.array([omega * np.sin(phi) for phi in u_phi])
    u_y = np.tile([u_y for i in range(spt)], 1).T.reshape(-1)
    return np.array([u_x, u_y]).T

u_array(T=T, n_pi=n_pi, spt=spt, target_Azz=target_Azz, rabi_period=rabi_period).shape

(80L, 2L)

In [14]:
def u_array_pi(**kwargs):
    return np.insert(u_array(**kwargs), pulse_locations(n_pi=kwargs['n_pi'], spt=kwargs['spt']) - np.arange(kwargs['n_pi']), np.array([0, 0]), 0)

u_array_pi(T=T, n_pi=n_pi, spt=spt, target_Azz=target_Azz, rabi_period=rabi_period)

array([[  5.00000000e-04,   0.00000000e+00],
       [  5.00000000e-04,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00],
       [  1.57079374e-06,  -4.99997533e-04],
       [  1.57079374e-06,  -4.99997533e-04],
       [  1.57079374e-06,  -4.99997533e-04],
       [  1.57079374e-06,  -4.99997533e-04],
       [  0.00000000e+00,   0.00000000e+00],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.99990130e-04,  -3.14157198e-06],
       [  0.00000000e+00,   0.00000000e+00],
       [ -4.71231922e-06,   4.99977794e-04],
       [ -4.71231922e-06,   4.99977794e-04],
       [ -4.71231922e-06,   4.99977794e-04],
       [ -4.71231922e-06,   4.99977794e-04],
       [  0.00000000e+00,   0.00000000e+00],
       [  4.99960522e-04,   6.28301994e-06],
       [  4.99960522e-04,   6.28301994e-06],
       [  4.99960522e-04,   6.28301994e-06],
       [  4.99960522e-04,   6.28301994e-06],
       [  

In [18]:
def delete_pi(u_array=None, n_pi=None, spt=None):
    return np.delete(u_array, pulse_locations(n_pi=n_pi, spt=spt), axis=0)

delete_pi(u_array_pi(T=T, n_pi=n_pi, spt=spt, target_Azz=target_Azz, rabi_period=rabi_period),
          n_pi=n_pi, spt=spt)

array([[  5.00000000e-04,   0.00000000e+00],
       [  5.00000000e-04,   0.00000000e+00],
       [  1.57079374e-06,  -4.99997533e-04],
       [  1.57079374e-06,  -4.99997533e-04],
       [  1.57079374e-06,  -4.99997533e-04],
       [  1.57079374e-06,  -4.99997533e-04],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.99990130e-04,  -3.14157198e-06],
       [ -4.71231922e-06,   4.99977794e-04],
       [ -4.71231922e-06,   4.99977794e-04],
       [ -4.71231922e-06,   4.99977794e-04],
       [ -4.71231922e-06,   4.99977794e-04],
       [  4.99960522e-04,   6.28301994e-06],
       [  4.99960522e-04,   6.28301994e-06],
       [  4.99960522e-04,   6.28301994e-06],
       [  4.99960522e-04,   6.28301994e-06],
       [  7.85365866e-06,  -4.99938316e-04],
       [  7.85365866e-06,  -4.99938316e-04],
       [  7.85365866e-06,  -4.99938316e-04],
       [  7.85365866e-06,  -4.99938316e-04],
       [ -