In [1]:
import numpy as np
from qutip_enhanced import *

### Only electron, no ps, detuning

In [2]:
base = {'det': [np.linspace(-0.1, 0.1, 3)],
        'ps': [np.array([[1.0, 1.0]])]}
print(misc.ensemble(base))

(array([[-0.1],
       [ 0. ],
       [ 0.1]]), array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]]), array([ 0.33333333,  0.33333333,  0.33333333]))


### Only electron, ps +-10%, no detuning    

In [3]:
base = {'det':  [np.array([0.0])],
        'ps': [np.array([[ps, ps] for ps in [.9, 1., 1.1]])]}
print(misc.ensemble(base))

(array([[ 0.],
       [ 0.],
       [ 0.]]), array([[ 0.9,  0.9],
       [ 1. ,  1. ],
       [ 1.1,  1.1]]), array([ 0.33333333,  0.33333333,  0.33333333]))


### Stuff

In [5]:
electron_ps = [.995, 1.0, 1.005]
nuclear_ps = [.9, 1.0, 1.1]
base = {'det': [np.linspace(-0.1, 0.1, 3), np.linspace(-50e-6, 50e-6, 3)],
        'ps': [np.array([[e, e] for e in electron_ps]), np.array([[n, n] for n in nuclear_ps]), np.array([[1.0]*4])]}
weight_base = {'det': [misc.f_drift(base['det'][0], fwhm=40e-3, drift_width=10e-3), misc.f_drift(base['det'][1], fwhm=50e-6)],
               # 'ps': [f_drift(electron_ps, fwhm=0.0025), f_drift(nuclear_ps, fwhm=0.0025), []]}
               'ps': [misc.f_drift(electron_ps, fwhm=0.01, center=1.0), misc.f_drift(nuclear_ps, fwhm=0.01, center=1.0), []]}
det, ps, weight = misc.ensemble(base, weight_base)
print(det.shape, ps.shape, weight.shape)
print(det)
print(ps)
print(weight)

((81L, 2L), (81L, 8L), (81L,))
[[-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1     -0.00005]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.     ]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [-0.1      0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.      -0.00005]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.     ]
 [ 0.       0.00005]
 [ 